# Quick links to the docs:
# - Redwood on Render: https://render.com/docs/deploy-redwood
# - Render's Blueprint spec: https://render.com/docs/yaml-spec

services:
- name: musician-booking-app-web
  type: web
  env: static
  buildCommand: corepack enable && yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist

  envVars:
  - key: SKIP_INSTALL_DEPS
    value: true

  routes:
  - type: rewrite
    source: /.redwood/functions/*
    # Replace `destination` here after your first deploy:
    destination: https://musician-booking-app-api.onrender.com/*
  - type: rewrite
    source: /*
    destination: /200.html

- name: musician-booking-app-api
  type: web
  plan: free
  env: node
  region: oregon
  buildCommand: corepack enable && yarn install && yarn rw build api
  startCommand: yarn rw deploy render api

  envVars:
  - key: DATABASE_URL
#     fromDatabase:
#       name: musician-booking-app-db
#       property: connectionString

# databases:
#   - name: musician-booking-app-db
#     region: oregon
